# Generated by Django 4.0.2 on 2022-03-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lasttname', models.CharField(max_length=100)),
                ('bod', models.DateField(max_length=8)),
                ('password', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
